#Adapted from http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/
#
matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
        - os: osx

install:
    - sudo ./install.sh

before_script:
    - export PATH=$PATH:/usr/local/bin
    - lcov --directory . --zerocounters

script:
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then make test; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then lcov --directory . --capture --output-file coverage.info; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then lcov --list coverage.info; fi #debug before upload

after_success:
