#Adapted from http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/
sudo: required
dist: trusty

install:
    # Install lcov, MPICH, zlib, OpenSSL, Gtest and LZ4
    - sudo apt-get -y install lcov mpich zlib1g-dev libssl-dev libgtest-dev liblz4-dev
    # Install Zstandard
    - wget https://github.com/facebook/zstd/archive/v1.0.0.tar.gz
    - tar xf v1.0.0.tar.gz
    - cd zstd-1.0.0
    - sudo make install PREFIX='/usr'
    - cd $TRAVIS_BUILD_DIR
    # Install Blosc
    - git clone https://github.com/Blosc/c-blosc 
    - cd c-blosc
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX='/usr' ..
    - cmake --build .
    - sudo cmake --build . --target install
    - cd $TRAVIS_BUILD_DIR
    # Install lcov to coveralls conversion + upload tool
    - gem install coveralls-lcov

before_script:
    - lcov --directory . --zerocounters

script:
    - make clean
    - make -j 4
    - make test -j 4 
    - lcov --directory . --capture --output-file coverage.info
    - lcov --list coverage.info # debug before upload

after_success:
